version: '2'
services:
  api:
    build: ./api
    volumes:
      # Mount local dir for development
      - "./api:/usr/src/api"
    ports:
      - "81:3000"
    links:
      - couchdb
    environment:
      NODE_ENV: production
      DB_HOST: "couchdb:5984"
    env_file:
      - ./api/.env_live.env

  couchdb:
    image: tutum/couchdb
    ports:
      - "5984:5984"
    env_file:
      - ./database/.env_test.env

  # web:
  #   build: ./web
  #   volumes:
  #     # Mount local dir for development
  #     - "./web:/usr/src/web"
  #   ports:
  #     - "80:3000"
  #   links:
  #     - api

  worker:
    build: ./worker
    volumes:
      # Mount local dir for development
      - "./worker:/usr/src/worker"
    # ports:
    #   - "80:3000"
    links:
      - couchdb
    environment:
      NODE_ENV: production
      DB_HOST: "couchdb:5984"
    env_file:
      - ./worker/.env_live.env
